### ISSUE TITLE
v.0.11 doesn't compile on stable rust

### ISSUE THREAD

**Issue by C0D3-M4513R** [AustinJ235/basalt#14]
Basalt uses these Feature assignments. They are NOT supported on stable rust. The library fails to build.
```
#![feature(arbitrary_self_types)]
#![feature(integer_atomics)]
#![feature(drain_filter)]
```

The error:```error[E0554]: `#![feature]` may not be used on the stable release channel```

**Comment by AustinJ235** [comment]
Personally I have used rust since the very early days, so my use of features has been extensive in the past. Rust stable is pretty far along and it turns out that I was pretty much stable compatible. I implemented drain filter functionality for the time being to allow this crate to be used on stable.

As of the latest master and release of 0.11.1 you should be good to go on stable.
